spring.application.name=api-gateway

# Puerto donde escucha el API Gateway
server.port=8080

# Ruta para las peticiones del User Service
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/user/**

# Ruta para las peticiones del Product Service
spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/product/**

# Configuración global de CORS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173

# Métodos HTTP permitidos
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS

# Headers HTTP permitidos
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*